require 'java'
require File.expand_path('../../apache-activemq-5.5.1/activemq-all-5.5.1.jar', __FILE__)
require File.expand_path('../../apache-activemq-5.5.1/lib/optional/log4j-1.2.14.jar', __FILE__)
require File.expand_path('../../apache-activemq-5.5.1/lib/optional/slf4j-log4j12-1.5.11.jar', __FILE__)
require File.expand_path('../../apache-activemq-5.5.1/lib/optional/spring-core-3.0.3.RELEASE.jar', __FILE__)
require File.expand_path('../../apache-activemq-5.5.1/lib/optional/spring-beans-3.0.3.RELEASE.jar', __FILE__)
require File.expand_path('../../apache-activemq-5.5.1/lib/optional/spring-context-3.0.3.RELEASE.jar', __FILE__)
require File.expand_path('../../apache-activemq-5.5.1/lib/optional/spring-asm-3.0.3.RELEASE.jar', __FILE__)
require File.expand_path('../../apache-activemq-5.5.1/lib/optional/spring-expression-3.0.3.RELEASE.jar', __FILE__)
require File.expand_path('../../apache-activemq-5.5.1/lib/optional/xbean-spring-3.7.jar', __FILE__)
require File.expand_path('../../apache-activemq-5.5.1/lib/jcl-over-slf4j-1.5.11.jar', __FILE__)
